# Basic CI build
name: Dev CI

# Controls when the action will run. Triggers the workflow on push
# events but only for the develop branch
on:
  push:
    branches: [ develop ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      - name: Dotnet build Sitecore v10.0
        run: dotnet build Glass.Mapper.sln --packages .\NuGetv100 --configfile .nuget\NuGet.Config -p:ScVersion=10.0.0
      
      - name: Dotnet build Sitecore v9.3
        run: dotnet build Glass.Mapper.sln --packages .\NuGetv93 --configfile .nuget\NuGet.Config -p:ScVersion=9.3.0
